service: your-express-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-north-1
  memorySize: 128
  timeout: 30

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true